// Copyright 2025 EURECOM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Contributors:
//   Giulio CAROTA
//   Thomas DU
//   Adlen KSENTINI

// Code generated by OpenAPI Generator (https://server-generator.tech); DO NOT EDIT.

/*
 * 3gpp-ue-address
 *
 * API for UE Address service. © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.1
 */

package northbound

import (
	"context"

	"gitlab.eurecom.fr/open-exposure/nef/ue-address/internal/models"
	"gitlab.eurecom.fr/open-exposure/nef/ue-address/internal/northbound/service"
)

type serverCtx interface {
	Service() *service.Service
}

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
	serverCtx
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService(serverCtx serverCtx) *DefaultAPIService {
	return &DefaultAPIService{serverCtx: serverCtx}
}

// RetrieveUEAddress - Retrieve UE Address.
func (s *DefaultAPIService) RetrieveUEAddress(ctx context.Context, ueAddressReq models.UeAddressReq) (models.ImplResponse, error) {
	// TODO - update RetrieveUEAddress with the required logic for this service method.
	// Add api_default_service.go to the .server-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	code, result, err := s.Service().RetrieveUeAddress(&ueAddressReq)
	if err != nil {
		return models.Response(code, models.ProblemDetails{Cause: err.Error()}), nil

	}
	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	return models.Response(code, result), nil
}
