// Copyright 2025 EURECOM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Contributors:
//   Giulio CAROTA
//   Thomas DU
//   Adlen KSENTINI

// Code generated by OpenAPI Generator (https://server-generator.tech); DO NOT EDIT.

/*
 * 3gpp-ue-address
 *
 * API for UE Address service. © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.1
 */

package northbound

import (
	"encoding/json"
	"net/http"
	"strings"

	"gitlab.eurecom.fr/open-exposure/nef/ue-address/internal/models"
)

// DefaultAPIController binds http requests to an api service and writes the service results to the http response
type DefaultAPIController struct {
	service      DefaultAPIServicer
	errorHandler models.ErrorHandler
}

// DefaultAPIOption for how the controller is set up.
type DefaultAPIOption func(*DefaultAPIController)

// WithDefaultAPIErrorHandler inject ErrorHandler into controller
func WithDefaultAPIErrorHandler(h models.ErrorHandler) DefaultAPIOption {
	return func(c *DefaultAPIController) {
		c.errorHandler = h
	}
}

// NewDefaultAPIController creates a default api controller
func NewDefaultAPIController(s DefaultAPIServicer, opts ...DefaultAPIOption) *DefaultAPIController {
	controller := &DefaultAPIController{
		service:      s,
		errorHandler: models.DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultAPIController
func (c *DefaultAPIController) Routes() models.Routes {
	return models.Routes{
		"RetrieveUEAddress": models.Route{
			Method:      strings.ToUpper("Post"),
			Pattern:     "/3gpp-ue-address/v1/retrieve",
			HandlerFunc: c.RetrieveUEAddress,
		},
	}
}

// RetrieveUEAddress - Retrieve UE Address.
func (c *DefaultAPIController) RetrieveUEAddress(w http.ResponseWriter, r *http.Request) {
	ueAddressReqParam := models.UeAddressReq{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&ueAddressReqParam); err != nil {
		c.errorHandler(w, r, &models.ParsingError{Err: err}, nil)
		return
	}
	if err := models.AssertUeAddressReqRequired(ueAddressReqParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := models.AssertUeAddressReqConstraints(ueAddressReqParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RetrieveUEAddress(r.Context(), ueAddressReqParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = models.EncodeJSONResponse(result.Body, &result.Code, w)
}
