// Copyright 2025 EURECOM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Contributors:
//   Giulio CAROTA
//   Thomas DU
//   Adlen KSENTINI

/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.3.0-alpha.4
 */

package models

// TrafficInfluSub - Represents a traffic influence subscription.
type TrafficInfluSub struct {

	// Identifies a service on behalf of which the AF is issuing the request.
	AfServiceId string `json:"afServiceId,omitempty"`

	// Identifies an application.
	AfAppId string `json:"afAppId,omitempty"`

	// Identifies an NEF Northbound interface transaction, generated by the AF.
	AfTransId string `json:"afTransId,omitempty"`

	// Identifies whether an application can be relocated once a location of the application has been selected.
	AppReloInd bool `json:"appReloInd,omitempty"`

	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\").
	Dnn string `json:"dnn,omitempty"`

	Snssai Snssai `json:"snssai,omitempty"`

	// string containing a local identifier followed by \"@\" and a domain identifier. Both the local identifier and the domain identifier shall be encoded as strings that do not contain any \"@\" characters. See Clauses 4.6.2 and 4.6.3 of 3GPP TS 23.682 for more information.
	ExternalGroupId string `json:"externalGroupId,omitempty"`

	// Each element identifies a group of users.
	ExternalGroupIds []string `json:"externalGroupIds,omitempty"`

	ExtSubscCats []string `json:"extSubscCats,omitempty"`

	// Identifies whether the AF request applies to any UE. This attribute shall set to \"true\" if applicable for any UE, otherwise, set to \"false\".
	AnyUeInd bool `json:"anyUeInd,omitempty"`

	// Identifies the requirement to be notified of the event(s).
	SubscribedEvents []SubscribedEvent `json:"subscribedEvents,omitempty"`

	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.
	Gpsi string `json:"gpsi,omitempty" validate:"regexp=^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$"`

	// string identifying a Ipv4 address formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166.
	Ipv4Addr string `json:"ipv4Addr,omitempty"`

	IpDomain string `json:"ipDomain,omitempty"`

	// string identifying a Ipv6 address formatted according to clause 4 in IETF RFC 5952. The mixed Ipv4 Ipv6 notation according to clause 5 of IETF RFC 5952 shall not be used.
	Ipv6Addr string `json:"ipv6Addr,omitempty"`

	// String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.
	MacAddr string `json:"macAddr,omitempty" validate:"regexp=^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$"`

	DnaiChgType DnaiChangeType `json:"dnaiChgType,omitempty"`

	// string formatted according to IETF RFC 3986 identifying a referenced resource.
	NotificationDestination string `json:"notificationDestination,omitempty"`

	// Set to true by the SCS/AS to request the NEF to send a test notification as defined in clause 5.2.5.3. Set to false or omitted otherwise.
	RequestTestNotification bool `json:"requestTestNotification,omitempty"`

	WebsockNotifConfig WebsockNotifConfig `json:"websockNotifConfig,omitempty"`

	// string formatted according to IETF RFC 3986 identifying a referenced resource.
	Self string `json:"self,omitempty"`

	// Identifies IP packet filters.
	TrafficFilters []FlowInfo `json:"trafficFilters,omitempty"`

	// Identifies Ethernet packet filters.
	EthTrafficFilters []EthFlowDescription `json:"ethTrafficFilters,omitempty"`

	// Identifies the N6 traffic routing requirement.
	TrafficRoutes []RouteToLocation `json:"trafficRoutes,omitempty"`

	// Reference to a pre-configured steering of user traffic to service function chain in downlink.
	SfcIdDl string `json:"sfcIdDl,omitempty"`

	// Reference to a pre-configured steering of user traffic to service function chain in uplink.
	SfcIdUl string `json:"sfcIdUl,omitempty"`

	// A String which is transparently passed to the UPF to be applied for traffic to SFC.
	Metadata *string `json:"metadata,omitempty"`

	TfcCorrInd bool `json:"tfcCorrInd,omitempty"`

	TempValidities []TemporalValidity `json:"tempValidities,omitempty"`

	// Identifies a geographic zone that the AF request applies only to the traffic of UE(s) located in this specific zone.
	// Deprecated
	ValidGeoZoneIds []string `json:"validGeoZoneIds,omitempty"`

	// Identifies geographical areas within which the AF request applies.
	GeoAreas []GeographicalArea `json:"geoAreas,omitempty"`

	AfAckInd bool `json:"afAckInd,omitempty"`

	AddrPreserInd bool `json:"addrPreserInd,omitempty"`

	// Indicates whether simultaneous connectivity should be temporarily maintained for the source and target PSA.
	SimConnInd bool `json:"simConnInd,omitempty"`

	// indicating a time in seconds.
	SimConnTerm int32 `json:"simConnTerm,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxAllowedUpLat int32 `json:"maxAllowedUpLat,omitempty"`

	// Contains EAS IP replacement information.
	EasIpReplaceInfos []EasIpReplacementInfo `json:"easIpReplaceInfos,omitempty"`

	// Indicates the EAS rediscovery is required for the application if it is included and set to \"true\".
	EasRedisInd bool `json:"easRedisInd,omitempty"`

	EventReq ReportingInformation `json:"eventReq,omitempty"`

	EventReports []EventNotification `json:"eventReports,omitempty"`

	// Indication of reporting candidate DNAI(s). If it is included and set to \"true\", the candidate DNAI(s) for the PDU session need to be reported. Otherwise set to \"false\" or omitted.
	CandDnaiInd bool `json:"candDnaiInd,omitempty"`

	TfcCorreInfo *TrafficCorrelationInfo `json:"tfcCorreInfo,omitempty"`

	PlmnId PlmnId `json:"plmnId,omitempty"`

	// Unsigned integer with valid values between 0 and 65535.
	PortNumber int32 `json:"portNumber,omitempty"`

	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SuppFeat string `json:"suppFeat,omitempty" validate:"regexp=^[A-Fa-f0-9]*$"`
}

// AssertTrafficInfluSubRequired checks if the required fields are not zero-ed
func AssertTrafficInfluSubRequired(obj TrafficInfluSub) error {
	return nil
	// if err := AssertSnssaiRequired(obj.Snssai); err != nil {
	// 	return err
	// }
	// for _, el := range obj.SubscribedEvents {
	// 	if err := AssertSubscribedEventRequired(el); err != nil {
	// 		return err
	// 	}
	// }
	// if err := AssertDnaiChangeTypeRequired(obj.DnaiChgType); err != nil {
	// 	return err
	// }
	// if err := AssertWebsockNotifConfigRequired(obj.WebsockNotifConfig); err != nil {
	// 	return err
	// }
	// for _, el := range obj.TrafficFilters {
	// 	if err := AssertFlowInfoRequired(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.EthTrafficFilters {
	// 	if err := AssertEthFlowDescriptionRequired(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.TrafficRoutes {
	// 	if err := AssertRouteToLocationRequired(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.TempValidities {
	// 	if err := AssertTemporalValidityRequired(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.GeoAreas {
	// 	if err := AssertGeographicalAreaRequired(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.EasIpReplaceInfos {
	// 	if err := AssertEasIpReplacementInfoRequired(el); err != nil {
	// 		return err
	// 	}
	// }
	// if err := AssertReportingInformationRequired(obj.EventReq); err != nil {
	// 	return err
	// }
	// for _, el := range obj.EventReports {
	// 	if err := AssertEventNotificationRequired(el); err != nil {
	// 		return err
	// 	}
	// }
	// if obj.TfcCorreInfo != nil {
	// 	if err := AssertTrafficCorrelationInfoRequired(*obj.TfcCorreInfo); err != nil {
	// 		return err
	// 	}
	// }
	// if err := AssertPlmnIdRequired(obj.PlmnId); err != nil {
	// 	return err
	// }
	// return nil
}

// AssertTrafficInfluSubConstraints checks if the values respects the defined constraints
func AssertTrafficInfluSubConstraints(obj TrafficInfluSub) error {
	return nil
	// if err := AssertSnssaiConstraints(obj.Snssai); err != nil {
	// 	return err
	// }
	// for _, el := range obj.SubscribedEvents {
	// 	if err := AssertSubscribedEventConstraints(el); err != nil {
	// 		return err
	// 	}
	// }
	// if err := AssertDnaiChangeTypeConstraints(obj.DnaiChgType); err != nil {
	// 	return err
	// }
	// if err := AssertWebsockNotifConfigConstraints(obj.WebsockNotifConfig); err != nil {
	// 	return err
	// }
	// for _, el := range obj.TrafficFilters {
	// 	if err := AssertFlowInfoConstraints(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.EthTrafficFilters {
	// 	if err := AssertEthFlowDescriptionConstraints(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.TrafficRoutes {
	// 	if err := AssertRouteToLocationConstraints(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.TempValidities {
	// 	if err := AssertTemporalValidityConstraints(el); err != nil {
	// 		return err
	// 	}
	// }
	// for _, el := range obj.GeoAreas {
	// 	if err := AssertGeographicalAreaConstraints(el); err != nil {
	// 		return err
	// 	}
	// }
	// if obj.MaxAllowedUpLat < 0 {
	// 	return &ParsingError{Param: "MaxAllowedUpLat", Err: errors.New(errMsgMinValueConstraint)}
	// }
	// for _, el := range obj.EasIpReplaceInfos {
	// 	if err := AssertEasIpReplacementInfoConstraints(el); err != nil {
	// 		return err
	// 	}
	// }
	// if err := AssertReportingInformationConstraints(obj.EventReq); err != nil {
	// 	return err
	// }
	// for _, el := range obj.EventReports {
	// 	if err := AssertEventNotificationConstraints(el); err != nil {
	// 		return err
	// 	}
	// }
	// if obj.TfcCorreInfo != nil {
	// 	if err := AssertTrafficCorrelationInfoConstraints(*obj.TfcCorreInfo); err != nil {
	// 		return err
	// 	}
	// }
	// if err := AssertPlmnIdConstraints(obj.PlmnId); err != nil {
	// 	return err
	// }
	// if obj.PortNumber < 0 {
	// 	return &ParsingError{Param: "PortNumber", Err: errors.New(errMsgMinValueConstraint)}
	// }
	// if obj.PortNumber > 65535 {
	// 	return &ParsingError{Param: "PortNumber", Err: errors.New(errMsgMaxValueConstraint)}
	// }
	// return nil
}
