// Copyright 2025 EURECOM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Contributors:
//   Giulio CAROTA
//   Thomas DU
//   Adlen KSENTINI

/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.3.0-alpha.4
 */

package models

// EventNotification - Represents a traffic influence event notification.
type EventNotification struct {

	// Identifies an NEF Northbound interface transaction, generated by the AF.
	AfTransId string `json:"afTransId,omitempty"`

	DnaiChgType DnaiChangeType `json:"dnaiChgType"`

	SourceTrafficRoute *RouteToLocation `json:"sourceTrafficRoute,omitempty"`

	SubscribedEvent SubscribedEvent `json:"subscribedEvent"`

	TargetTrafficRoute *RouteToLocation `json:"targetTrafficRoute,omitempty"`

	// DNAI (Data network access identifier), see clause 5.6.7 of 3GPP TS 23.501.
	SourceDnai string `json:"sourceDnai,omitempty"`

	// DNAI (Data network access identifier), see clause 5.6.7 of 3GPP TS 23.501.
	TargetDnai string `json:"targetDnai,omitempty"`

	// The candidate DNAI(s) for the PDU Session.
	CandidateDnais []string `json:"candidateDnais,omitempty"`

	// If provided and set to true, it indicates that the candidate DNAIs provided in the candidateDnais attribute are in descending priority order, i.e., the lower the array index the higher the priority of the respective DNAI. If omitted, the default value is false.
	CandDnaisPrioInd bool `json:"candDnaisPrioInd,omitempty"`

	// Indication of EAS re-discovery. If present and set to \"true\", it indicates the EAS re-discovery is performed, e.g. due to change of common EAS. Default value is \"false\" if omitted. May be included for event \"UP_PATH_CHANGE\".
	EasRediscoverInd bool `json:"easRediscoverInd,omitempty"`

	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.
	Gpsi string `json:"gpsi,omitempty" validate:"regexp=^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$"`

	// string identifying a Ipv4 address formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166.
	SrcUeIpv4Addr string `json:"srcUeIpv4Addr,omitempty"`

	SrcUeIpv6Prefix Ipv6Prefix `json:"srcUeIpv6Prefix,omitempty"`

	// string identifying a Ipv4 address formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166.
	TgtUeIpv4Addr string `json:"tgtUeIpv4Addr,omitempty"`

	TgtUeIpv6Prefix Ipv6Prefix `json:"tgtUeIpv6Prefix,omitempty"`

	// String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.
	UeMac string `json:"ueMac,omitempty" validate:"regexp=^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$"`

	// string formatted according to IETF RFC 3986 identifying a referenced resource.
	AfAckUri string `json:"afAckUri,omitempty"`
}

// AssertEventNotificationRequired checks if the required fields are not zero-ed
func AssertEventNotificationRequired(obj EventNotification) error {
	elements := map[string]interface{}{
		"dnaiChgType":     obj.DnaiChgType,
		"subscribedEvent": obj.SubscribedEvent,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertDnaiChangeTypeRequired(obj.DnaiChgType); err != nil {
		return err
	}
	if obj.SourceTrafficRoute != nil {
		if err := AssertRouteToLocationRequired(*obj.SourceTrafficRoute); err != nil {
			return err
		}
	}
	if err := AssertSubscribedEventRequired(obj.SubscribedEvent); err != nil {
		return err
	}
	if obj.TargetTrafficRoute != nil {
		if err := AssertRouteToLocationRequired(*obj.TargetTrafficRoute); err != nil {
			return err
		}
	}
	if err := AssertIpv6PrefixRequired(obj.SrcUeIpv6Prefix); err != nil {
		return err
	}
	if err := AssertIpv6PrefixRequired(obj.TgtUeIpv6Prefix); err != nil {
		return err
	}
	return nil
}

// AssertEventNotificationConstraints checks if the values respects the defined constraints
func AssertEventNotificationConstraints(obj EventNotification) error {
	if err := AssertDnaiChangeTypeConstraints(obj.DnaiChgType); err != nil {
		return err
	}
	if obj.SourceTrafficRoute != nil {
		if err := AssertRouteToLocationConstraints(*obj.SourceTrafficRoute); err != nil {
			return err
		}
	}
	if err := AssertSubscribedEventConstraints(obj.SubscribedEvent); err != nil {
		return err
	}
	if obj.TargetTrafficRoute != nil {
		if err := AssertRouteToLocationConstraints(*obj.TargetTrafficRoute); err != nil {
			return err
		}
	}
	if err := AssertIpv6PrefixConstraints(obj.SrcUeIpv6Prefix); err != nil {
		return err
	}
	if err := AssertIpv6PrefixConstraints(obj.TgtUeIpv6Prefix); err != nil {
		return err
	}
	return nil
}
